version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies (if any)..."
  build:
    commands:
      - echo "Building the static website..."
  post_build:
    commands:
      - echo "Copying files to S3..."
      - aws s3 cp . s3://greencycle-static-site/ --recursive

artifacts:
  files:
    - '**/*'
